name: doctor_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  khalti_flutter: ^3.0.0
  lottie: ^2.7.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
